

import colors from "./colors.js"

const styles = {
  itemContainer: {
    display: "flex",
    flexDirection: "column",
    borderBottomWidth: 1,
    borderStyle: "solid",
    borderBottomColor: colors.inboxBorderGrey,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderRadius: 4,
    width: 340,
  },
  surveyBackground: { backgroundColor: colors.white },
  surveyStartContainer: {
    display: "flex",
    flexDirection: "column",
    borderBottomWidth: 1,
    borderStyle: "solid",
    borderBottomColor: colors.inboxBorderGrey,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginHorizontal: 8,
    borderRadius: 4,
  },
  takeSurveyButtonRespond: {
    backgroundColor: colors.blue,
    color: colors.white,
    marginLeft: "68%",
    marginTop: 5,
    width: 100,
    height: 32,
  },
  takeSurveyButtonResume: {
    backgroundColor: colors.green,
    color: colors.white,
    marginLeft: "68%",
    marginTop: 5,
    width: 100,
    height: 32,
  },
  takeSurveyButtonText: {
    color: colors.white,
    marginLeft: "68%",
    textAlignVertical: "center",
    paddingTop: 5,
    fontSize: 10,
  },
  surveyTitlePage: {
    marginTop: 12,
    marginLeft: 10,
    marginBottom: 17,
    fontSize: 30,
  },
  surveyContinueButton: {
    backgroundColor: colors.green,
    color: colors.white,
    marginTop: "auto",
    width: 125,
  },
  surveyButton: {
    backgroundColor: colors.green,
    color: colors.white,
    marginTop: "auto",
    alignSelf: "stretch",
    width: "35%",
  },
  surveyButtonText: {
    color: colors.white,
    alignSelf: "stretch",
    width: "100%",
    fontSize: 15,
  },
  surveyButtonDisabled: {
    backgroundColor: colors.darkBlueGray,
    color: colors.white,
    marginTop: "auto",
    alignSelf: "stretch",
    width: "35%",
  },
  setFontSizeOne: {
    fontSize: 15,
  },
  setFontSizeTwo: {
    fontSize: 20,
  },
  setFontSizeThree: {
    fontSize: 25,
  },
  setFontSizeFour: {
    fontSize: 35,
  },
  option: {
    fontSize: 12,
    color: colors.black,
    textAlign: "left",
  },
  radioButtons: {
    marginBottom: 25,
  },
  unSelected: {
    borderColor: colors.blueGray,
    borderWidth: 2,
    width: 160,
    margin: 2,
    padding: 10,
    borderRadius: 10,
  },
  selected: {
    borderColor: colors.green,
    width: 160,
    margin: 3,
    padding: 10,
    borderRadius: 10,
    borderWidth: 3,
  },
  submitContainer: {
    display: "flex",
    flexDirection: "column",
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: colors.white,
    marginBottom: 32,
    marginHorizontal: 8,
    borderRadius: 4,
    height: 75,
  },
  inboxContainer: {
    display: "flex",
    flexDirection: "column",
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 0.25,
    borderBottomColor: colors.inboxBorderGrey,
    elevation: 0,
    marginTop: 5,
    marginBottom: 8,
    marginHorizontal: 8,
  },
  submitPageContainer: {
    display: "flex",
    flexDirection: "column",
    borderBottomWidth: 1,
    borderStyle: "solid",
    borderBottomColor: colors.lightGray,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "black",
    shadowOpacity: 0.26,
    shadowOffset: { width: 0, height: -2 },
    shadowRadius: 10,
    backgroundColor: colors.white,
    elevation: 1,
    marginBottom: 8,
    marginHorizontal: 8,
    borderRadius: 4,
    height: 350,
  },
  qNo: {
    backgroundColor: colors.qsnoBg,
    borderRadius: 200,
    width: 30,
    color: colors.white,
    elevation: 3,
    fontSize: 8,
    marginLeft: 277,
    marginTop: 4,
    marginBottom: 30,
    fontStyle: "italic",
  },
  qType: {
    backgroundColor: colors.blue,
    marginHorizontal: 8,
    height: 23,
    borderRadius: 5,
    color: colors.white,
    elevation: 3,
    textAlign: "center",
    textAlignVertical: "center",
    paddingHorizontal: 10,
  },

  surveyQuestion: {
    backgroundColor: colors.questionBg,
    borderRadius: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  incentive: {
    fontSize: 12,
    backgroundColor: colors.goldenYellow,
    marginHorizontal: 3,
    height: 20,
    color: colors.black,
    borderRadius: 5,
    textAlign: "center",
    textAlignVertical: "center",
    paddingLeft: 4,
    paddingRight: 4,
  },
  totalIncentive: {
    backgroundColor: colors.goldenYellow,
    marginHorizontal: 8,
    height: 30,
    color: colors.black,
    elevation: 3,
    borderRadius: 30,
    textAlign: "center",
    textAlignVertical: "center",
    paddingHorizontal: 10,
  },

  ratingSelected: {
    borderColor: colors.green,
    flexDirection: "row",
    margin: 5,
    borderRadius: 30,
    borderWidth: 2,
    marginRight: 9,
  },

  ratingUnSelected: {
    borderColor: colors.blueGray,
    display: "flex",
    flexDirection: "row",
    margin: 5,
    borderRadius: 30,
    borderWidth: 2,
    marginRight: 9,
  },
  ratingOption: {
    color: colors.black,
  },
  ratingContainer: {
    display: "flex",
    flexDirection: "column",
    borderBottomWidth: 1,
    borderStyle: "solid",
    borderBottomColor: colors.lightGray,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "black",
    shadowOpacity: 0.26,
    shadowOffset: { width: 0, height: -2 },
    shadowRadius: 10,
    backgroundColor: colors.white,
    elevation: 1,
    marginBottom: 8,
    marginHorizontal: 8,
    borderRadius: 4,
    width: 340,
  },
  descriptiveContainer: {
    backgroundColor: colors.gray2,
    height: 150,
    borderRadius: 6,
  },
  requiredIndicator: {
    backgroundColor: colors.red,
    color: colors.white,
    borderRadius: 20,
    fontWeight: "bold",
    width: 70,
    height: 20,
    textAlign: "center",
  },

  requiredIconCircle: {
    backgroundColor: colors.red,

    borderRadius: 20,
    marginVertical: 4,
    width: 20,
    height: 20,
  },
  requiredIconText: {
    fontWeight: "bold",
    fontSize: 30,
    textAlign: "center",
    color: colors.white,
    marginVertical: -6,
  },
  answerLimit: {
    marginHorizontal: 279,
    marginVertical: 5,
    width: 40,
    height: 20,
    color: colors.black,
    textAlign: "center",
    textAlignVertical: "center",
    marginBottom: 7,
  },
  surveyResultHK: {
    backgroundColor: colors.goldenYellow,
    width: 140,
    height: 45,
    color: colors.black,
    elevation: 3,
    borderRadius: 30,
    marginHorizontal: 90,
  },
  surveyRecordMeta: {
    fontSize: 5,
    marginHorizontal: 8,
    marginVertical: 2,
    height: 20,
    color: colors.black,
    borderRadius: 30,
    textAlign: "center",
    textAlignVertical: "center",
    paddingHorizontal: 10,
    fontStyle: "italic",
  },
  surveyTitle: {
    paddingLeft: 5,
    paddingTop: 12,
    textAlignVertical: "center",
    paddingBottom: -20,
    fontWeight: "bold",
    fontSize: 20,
  },
  titleBg: {
    backgroundColor: colors.titleBgGrey,
    borderRadius: 10,
  },
  pointMeta: {
    fontSize: 12,
    height: 20,
    color: colors.black,
    textAlign: "center",
    textAlignVertical: "center",
    paddingHorizontal: 6,
    fontWeight: "bold",
  },
  otherMeta: {
    fontSize: 12,
    height: 20,
    color: colors.black,
    marginLeft: "auto",
    marginRight: 4,
    textAlignVertical: "center",
    textAlign: "right",
    fontStyle: "italic",
  },

  stickyTopBar: {
    height: 30,
    backgroundColor: colors.topBarBg,
    textAlignVertical: "center",
    paddingLeft: 25,
    fontStyle: "italic",
  },
  nearestQuestions: {
    backgroundColor: colors.goldenYellow,
    marginHorizontal: 8,
    height: 20,
    width: 20,
    color: colors.black,
    borderRadius: 30,
    textAlign: "center",
    textAlignVertical: "center",
    fontWeight: "bold",
    fontSize: 10,
  },
  nearestQuestionsText: {
    backgroundColor: colors.goldenYellow,
    marginVertical: 3,
    color: colors.black,
    borderRadius: 30,
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 10,
  },
  topBarText: {
    fontStyle: "italic",
  },
  topBarContent: {
    marginLeft: 10,
  },
  filterChip: {
    marginLeft: 6,
    fontSize: 2,
    elevation: 1,
    borderWidth: 0.5,
    borderColor: colors.black,
  },
  filterContainer: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "white",
    padding: 8,
    borderRadius: 4,
    shadowColor: "black",
  },
  surveySpinner: {
    marginVertical: 200,
  },
  noSurveyFound: {
    textAlign: "center",
    fontSize: 15,
    fontWeight: "300",
    textAlignVertical: "center",
    //marginTop:'auto',
    //padding:'auto'
  },
  surveyOrderByIcon: {
    marginLeft: 6,
    backgroundColor: colors.white,
    borderRadius: 50,
    elevation: 1.5,
    borderWidth: 0.5,
  },
  surveyDropDownContainerStyle: {
    backgroundColor: "#dfdfdf",
    borderWidth: 0.5,
    marginLeft: 23,
    marginTop: 10,
    width: 105,
  },
  surveyDropDownPickerStyle: {
    width: 105,
    borderWidth: 0.5,
    borderRadius: 5,
    elevation: 1,
    minHeight: 30,
    marginTop: 9,
    marginLeft: 23,
  },
}

export default styles